language: python
python:
  - 2.7
install: 
  - pip install . --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install -r test-requirements.txt --use-mirrors
script: 
  - "pep8 --ignore=E501,E225,E128 amazon"
  - "sphinx-build -nW -b html -d _build/doctrees . _build/html"
